### ISSUE TITLE
hello,po主你好，我最近也在做这个lab，现在做lab7的时候遇到一个问题，想知道你现在lab7能顺利按照assignment完成吗？ #1

### ISSUE THREAD

**Issue by RedemptionC** [PKUFlyingPig/CS144-Computer-Network#1]
我遇到的问题是，当client想要建立连接（发出SYN），中间需要查询server side的network Interface（10.0.0.172）的mac地址，但是发出的ARP request得不到响应，想知道是不是cs144.keithw.org的原因

**Comment by PKUFlyingPig** [comment]
cs144.keithw.org服务器可能宕机了，你可以试着在CS144开课的时候试一下。

**Comment by RedemptionC** [comment]
> cs144.keithw.org服务器可能宕机了，你可以试着在CS144开课的时候试一下。
QAQ 那得等好久诶
BTW 我试了下你的代码，很多test过不了，是我操作的问题吗

**Comment by PKUFlyingPig** [comment]
我本地虚拟机上是通过了所有测试的。

**Comment by RedemptionC** [comment]
> 我本地虚拟机上是通过了所有测试的。

soga 可能是我操作的问题
anyway 感谢回复><
